// frontend/src/app/auth/confirmed/page.tsx
import { Link } from "lucide-react";

type Props = {};
function page({}: Props) {
    return (
        <section className="flex-1 flex items-center justify-center flex-col gap-10">
            <h2 className="text-4xl text-green-600">
                Thank you for Confirming Your Email
            </h2>
            <h3 className="text-2xl text-green-400">You can now Login</h3>
            <Link className="bg-blue-500 p-4 w-full" href="/auth/login">
                Login
            </Link>
        </section>
    );
}
export default page;

// front-end/src/routes/auth/confirmed/+page.svelte
<script>
	import { happyEmoji } from '$lib/utils/constant';
</script>

<svelte:head>
	<title>Auth - Account activated | Actix Web & SvelteKit</title>
</svelte:head>
<div class="flex items-center justify-center h-[60vh]">
	<div
		class="w-11/12 md:w-2/3 lg:w-1/3 rounded-xl flex flex-col items-center divide-y bg-slate-800 py-4"
	>
		<h1 class="text-center text-2xl font-bold text-sky-400 mb-2">Email address confirmed</h1>

		<p class="text-sky-400 text-justify px-4 py-4">
			Your account has been activated successfully {happyEmoji}!!! You can now
			<a href="/auth/login" class="ml-2 text-slate-400 underline hover:text-sky-400"> Login. </a>
		</p>
	</div>
</div>
